<?php $posts = $this->getPosts(); ?>
 <div class="page-title-blog">
    <h1><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h1>
</div>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<div class="blog-wrapper sn-blog">
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        
		<?php
			$pattern = "/<img .+\/>/";
			$subject = $post->getPostContent();
			$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
			$matched =$matches[0];
			$first_img=$matched[0];
			//print_r($first_img);
		?>
		<?php if($first_img !=NULL){ ?>
		<div class="img-blog-list">
			<div class="overlay-image">
				<a class="quick-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>"></a>
			</div>
			<?php //var_dump($first_img);?>
			<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo($first_img);?></a>
		</div>
		<?php }?>
		<div class="info-wrapper-blog">
			<div class="postTitle">
	            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
	            <p class="date-blog"><?php echo $post->getCreatedTime(); ?></p>
	        </div>
			<div class="blog-info">
				<div class="postContent">
					<?php $text = str_replace($first_img, '', $post->getPostContent()); 
						$html = strip_tags($text);
						echo substr($html,1,500);
					?>

				</div>
			</div>
			<div class="bottom-blog-list">
				
				<div class="postDetails">
					<?php if ($this->getCommentsEnabled()): ?>
						<?php echo $post->getCommentCount(); ?> <a style="color: red;"href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
					<?php endif; ?>
					<?php $postCats = $post->getCats(); ?>
					<?php if (!empty($postCats)): ?>
						<?php echo Mage::helper('blog')->__('Posted in'); ?>
						<?php foreach ($postCats as $data): ?>
							<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
						<?php endforeach; ?>
					<?php else: ?>
						<?php echo Mage::helper('blog')->__('Posted'); ?>
					<?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
				</div>
			</div>
		</div>
    </div>
<?php endforeach; ?>
</div>
<div class="toolbar-blog">
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
</div>
