<?php $posts = $this->getPosts(); ?>
<?php
	
?>
<div class="latest-blogs">
	<div class="block-title" style="position: relative;">
		<strong>
			<span><?php echo $this->__('New Blog')?></span>
		</strong>
		<div class="sn-img icon-bacsic sn-blog"></div>
		
		<div class="customNavigation nav-left-blog" style="display: none;">
			<a class="btn-bs prev-blog icon-angle-left" title="Previous"></a>
			<a class="btn-bs next-blog icon-angle-right" title="Next"></a>
		</div>
	</div>
	<div class="block latest-blog">

		
		<div class="block-content">
			<div class="latest-blog-slider">
				<?php $i=0; foreach ($posts as $post): ?>
				<div class="item-blog item">
					<?php
						$pattern = "/<img .+\/>/";
						$subject = $post->getPostContent();
						$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
						$matched =$matches[0];
						$first_img=$matched[0];
					?>
					<div class="img-blog">
						<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo($first_img);?></a>
					</div>
					<div class="blog-info">
						<div class="postTitle">
							<h2><a title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
						</div>
						
						<div class="postContent">
							<?php $text = str_replace($first_img, '', $post->getPostContent()); 
								$html = strip_tags($text);
								echo substr($html,1,123);
							?>
						</div>
					</div>
				</div>
				<?php $i++;?>
				
				<?php if($i==3) break;?>
				<?php endforeach; ?>
			</div>
		</div>
		<script>
			jQuery(document).ready(function($) {
				var owl_blog = $(".latest-blog-slider");
				owl_blog.owlCarousel({
					itemsCustom : [
					[0, 1],
					[480, 2],
					[768, 3],
					[992, 1],
					[1200, 1]
					], 

					slideSpeed : 300,
					stopOnHover: true,
					paginationSpeed : 400,
					autoPlay:true,
					pagination: true,
				});	  
				
				
				$(".nav-left-blog .next-blog").click(function(){
					owl_blog.trigger('owl.next');
				})
				$(".nav-left-blog .prev-blog").click(function(){
					owl_blog.trigger('owl.prev');
				})
			});	
		</script>
	</div>
</div>