<?php $posts = $this->getPosts(); ?>
<?php
	
?>
<div class="latest-blogs">
	<div class="block-title" style="position: relative;">
		<strong>
			<span><?php echo $this->__('New Blog')?></span>
			<a class="sn-view" title="123" href="#" >View All</a>
		</strong>
			
	</div>
	<div class="block latest-blog">

		
		<div class="block-content">
			<div class="latest-blog-slider">
				<?php $i=0; foreach ($posts as $post): ?>
				<div class="item-blog item">
					<?php
						$pattern = "/<img .+\/>/";
						$subject = $post->getPostContent();
						$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
						$matched =$matches[0];
						$first_img=$matched[0];
					?>
					<div class="img-blog">
						<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo($first_img);?></a>
						<!-- <p class="date-blog"><?php //echo $post->getCreatedTime(); ?></p> -->
						<?php $_ct= new Zend_Date($post->getCreatedTime());?> 
        				<div class="sn-datev2">
							<?php $date_create = $post->getCreatedTime();?>
							<div class="d-blog">
								<?php 
									$day_blog = date("d",strtotime($date_create));
									echo $day_blog;
								?>
							</div>
							<div class="m-blog">
								<?php 
									$month_blog = date("M",strtotime($date_create));
									echo $month_blog;
								?>	
							</div>
						</div>			
            		</div>
					<div class="blog-info">
						<div class="postTitle">
							<h2><a title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
						</div>
						
						<div class="postContent">
							<?php $text = str_replace($first_img, '', $post->getPostContent()); 
								$html = strip_tags($text);
								echo substr($html,1,170);
							?>
						</div>
					</div>
				</div>
				<?php $i++;?>
				
				<?php if($i==2) break;?>
				<?php endforeach; ?>
			</div>
		</div>
		
	</div>
</div>