

        <?php if ($posts = $this->getRecent()): ?>
			<div class="block recent-posts">
				<div class="block-title">
					<strong><span><?php echo Mage::helper('blog')->__('Recent Posts'); ?></span></strong>
				</div>
				<div class="block-content">
					<ul>
						<?php foreach ($posts as $post): ?>
						<li><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
        <?php endif; ?>

		
        <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
            <div class="categories-blog">
				<div class="block-title">
					<strong><span><?php echo Mage::helper('blog')->__('Categories'); ?></span></strong>
				</div>
				<div class="block-content">
					<ul>
						<?php $cats = $this->getCategories(); ?>
						<?php foreach ($cats as $cat): ?>
							<li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
						<?php endforeach; ?>
					</ul>
				</div>
            </div>
        <?php endif; ?>

        <?php echo $this->getChildHtml('blog_tags'); ?>
