<div class="header-v0 header-v2">
	<div class="yt-header-top">
		<div class="container">
			<div class="row">
				
				<div class="col-lg-10 col-md-10 col-sm-9 col-xs-12" style="float:right">
					<div class="yt-header-topv2">
						<div class="row">
							<div class="col-lg-6 col-md-5 sl-header-text">
								<?php echo $this->getChildHtml('header-slider');?>
							</div>
							<!-- LANGUAGE_CURENCY -->
							<div class="col-lg-6 col-md-7 top-links-action">
								<?php echo $this->getChildHtml('store_language') ?>
								<?php echo $this->getChildHtml('currency'); ?>					
								<div class="block-action-header top-link-account my-account-link">
									<ul>
										<li>
											<a class="account-toplink dropdown-ict" title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>"><?php echo $this->__('My Account')?></a>
											<div class="dropdown-link-account">
												<?php echo $this->getChildHtml('topLinks');?>
											</div>
										</li>
									</ul>
								</div>
								<!-- MYLOGIN -->
								<div class="block-action-header top-link-account login-link">
									<ul>
										<?php if(!$this->helper('customer')->isLoggedIn()){?>
										<li>
											<a class="login-btn" data-toggle="modal" data-target="#modal-login" title="<?php echo $this->__('Login')?>"><?php echo $this->__('Login')?></a>
			                                <?php echo $this->getChildHtml('customer_form_mini_login'); ?>
										</li>
										<?php } else{?>
										<li>
											<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>"><?php echo $this->__('Logout');?></a>
			                            </li>
										<?php } ?>
									</ul>
								</div>
								<!-- END LOGIN -->
								
								<div class="action-mobile">

									<div class="block-action-header top-link-account my-account-link account-mobile-btn">
										<ul>
											<li>
												<a class="acc-mobile" title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>">&nbsp;</a>
											</li>
										</ul>
										<div class="dropdown-mobile">
											<?php echo $this->getChildHtml('topLinks');?>
										</div>
									</div>
									
									<div class="block-action-header top-link-account login-link login-mobile-btn">
										<ul>
											<?php if(!$this->helper('customer')->isLoggedIn()){?>
											<li>
												<a class="login-btn" href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo $this->__('Login')?>">&nbsp;</a>
											</li>
											<?php } else{?>
											<li>
												<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>">&nbsp;</a>
											</li>
											<?php } ?>
										</ul>
									</div>
									
								</div>
							</div>
						</div>
					</div>
					<div class="yt-header-middle">
						
							<div class="row">							
								<div class="col-lg-12 col-md-12 col-sm-12 yt-megamenu">
									<div class="yt-header-under">
										<div class="yt-menu">
											<?php echo $this->getChildHtml('megaMenu') ?>
										</div>
										
										<div class="yt-searchpro">
											<a class="btn-search-mobilev2 icon-search" href="javascript:void(0)" title="<?php echo $this->__('Search')?>"></a>
											<?php echo $this->getChildHtml('searchboxpro'); ?>
											<script>
												jQuery(document).ready(function($){
													$( ".btn-search-mobilev2" ).click(function() {
														$('.form-search').toggleClass('show')
														$(this).toggleClass('active')
													});
												});
											</script>
										</div>
										<div class="mini-cart-header">
											<?php echo $this->getChildHtml('mini-cartpro') ?>
										</div>
										
									</div>
									
								</div>

							</div>
						
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-3 col-xs-12 logo-wrapper" style="float: left">
					<div class="logo-wrapperv2">
						<h1>
							<a title="<?php echo $this->getLogoAlt() ?>" href="<?php echo $this->getUrl('') ?>">
								<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
							</a>
						</h1>
					</div>
				</div>
			</div>
			<!-- RESPOSIVE MENU MEGA -->

			<div class="yt-responsivemenu-v2">
				<div id="yt-responsivemenu" class="yt-responsivemenu">
					<?php echo $this->getChildHtml('mobiMenu'); ?>
				</div>	
			</div>		
		</div>
		<!-- END CONTAINER -->
	</div>
	
	

	
</div>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$i = 0;	   
		$('#yt_left .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li.sm_megamenu_lv1').each(function(){
			$this = $(this);
			$i ++; 
			if( $i > 11 ){ 
				$this.css({'display':'none'});
			}  
			if( $i == 11 )  {
				$('#yt_left .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu').append('<div class="more-wrap"><a href="<?php echo $this->getUrl('all-categories')?>"><?php echo $this->__("All Categories"); ?></div>');
			}
		});
	})
</script>
