<?php 
global $var_yttheme;
?>
<div class="socials-wrap">
	<ul>
		<?php if( $var_yttheme->getParam('show_facebook') == 1 ){ ?>
			<li><a class="icon-facebook show_facebook" title="<?php echo $var_yttheme->getParam('facebook_name');?>" href="<?php echo $var_yttheme->getParam('facebook_url');?>" target="_blank" data-icon="f"><span><?php echo $var_yttheme->getParam('facebook_name');?></span></a></li>
		<?php }?>
		<?php if( $var_yttheme->getParam('show_twitter') == 1 ){ ?>
			<li><a class="icon-twitter show_twitter" title="<?php echo $var_yttheme->getParam('twitter_name');?>" href="<?php echo $var_yttheme->getParam('twitter_url');?>" target="_blank" data-icon="l"><span><?php echo $var_yttheme->getParam('twitter_name');?></span></a></li>
		<?php }?>
		<?php if( $var_yttheme->getParam('show_google') == 1 ){ ?>
			<li><a class="icon-google-plus show_google" title="<?php echo $var_yttheme->getParam('google_name');?>" href="<?php echo $var_yttheme->getParam('google_url');?>" target="_blank" data-icon="g"><span><?php echo $var_yttheme->getParam('google_name');?></span></a></li>
		<?php }?>
		
		<?php if( $var_yttheme->getParam('show_pinterest') == 1 ){ ?>
			<li><a class="icon-pinterest show_pinterest" title="<?php echo $var_yttheme->getParam('pinterest_name');?>" href="<?php echo $var_yttheme->getParam('pinterest_url');?>" target="_blank" data-icon="&"><span><?php echo $var_yttheme->getParam('pinterest_name');?></span></a></li>
		<?php }?>	
		
		<?php if( $var_yttheme->getParam('show_linkedin') == 1 ){ ?>
			<li><a class="icon-linkedin show_linkedin" title="<?php echo $var_yttheme->getParam('linkedin_name');?>" href="<?php echo $var_yttheme->getParam('linkedin_url');?>" target="_blank" data-icon="i"><span><?php echo $var_yttheme->getParam('linkedin_name');?></span></a></li>
		<?php }?>

	</ul>
</div>    
			
