<?php
    // Check if current Magento version includes Persistent Shopping Cart Extension
    $isPersistantShoppingCartEnabled = Mage::getStoreConfigFlag('persistent/options/enabled');
    $isContextCheckout = 0;
    if ($isPersistantShoppingCartEnabled) {
        $html = $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml();
        $isContextCheckout = Mage::helper('checkout')->isContextCheckout();
    } else {
        $html = $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml();
    }
?>

<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('paypalauth.register'); ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
		<div class="row">
        <div class="fieldset col-lg-6 col-md-6">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $html ?>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="document_type" class="required"><em>*</em><?php echo $this->__('Tipo de Documento') ?></label>
                        <div class="input-box">
                            <?php
                            $attribute = Mage::getModel('eav/config')->getAttribute('customer','document_type');
                            $options = $attribute->getSource()->getAllOptions(false);
                            ?>
                            <select id="document_type" name="document_type" title="<?php echo $this->__('Tipo de Documento') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Seleccione Tipo Documento') ?></option>
                                <?php
                                foreach($options as $option){
                                    ?>
                                    <option value='<?php echo $option['value']?>' <?php if($this->getFormData()->getDocumentType() == $option['value']){ echo 'selected="selected"';}?>><?php echo $this->__($option['label'])?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="document_number" class="required"><em>*</em><?php echo $this->__('Número de Documento') ?></label>
                        <div class="input-box">
                            <input type="text" name="document_number" id="document_number" value="<?php echo $this->htmlEscape($this->getFormData()->getDocumentNumber()) ?>" title="<?php echo $this->__('Número de Documento') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="email_type" class="required"><em>*</em><?php echo $this->__('Tipo de Email') ?></label>
                        <div class="input-box">
                            <?php
                            $attribute = Mage::getModel('eav/config')->getAttribute('customer','email_type');
                            $options = $attribute->getSource()->getAllOptions(false);
                            ?>
                            <select id="email_type" name="email_type" title="<?php echo $this->__('Tipo de Email') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Seleccione Tipo Email') ?></option>
                                <?php
                                foreach($options as $option){
                                    ?>
                                    <option value='<?php echo $option['value']?>' <?php if($this->getFormData()->getEmailType() == $option['value']){ echo 'selected="selected"';}?>><?php echo $this->__($option['label'])?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="mobile" class="required"><?php echo $this->__('Celular') ?></label>
                        <div class="input-box">
                            <input type="text" name="mobile" id="mobile" value="<?php echo $this->htmlEscape($this->getFormData()->getMobile()) ?>" title="<?php echo $this->__('Celular') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
                        <?php endif ?>
                    </div>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6" style="margin-bottom:5px;">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="lead_source"><?php echo $this->__('¿Como conoció de DentalDoktor?') ?></label>
                        <div class="input-box">
                            <?php
                            $attribute = Mage::getModel('eav/config')->getAttribute('customer','lead_source');
                            $options = $attribute->getSource()->getAllOptions(false);
                            ?>
                            <select id="lead_source" name="lead_source" title="<?php echo $this->__('¿Como conoció de DentalDoktor?') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Seleccione Una Opción') ?></option>
                                <?php
                                foreach($options as $option){
                                    ?>
                                    <option value='<?php echo $option['value']?>' <?php if($this->getFormData()->getLeadSource() == $option['value']){ echo 'selected="selected"';}?>><?php echo $this->__($option['label'])?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6" style="margin-top: 10px;">
                        <?php if ($this->isNewsletterEnabled()): ?>
                        <div class="input-box">
                            <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        </div>
                        <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                        <?php endif ?>
                        <div class="input-box">
                            <input type="checkbox" name="habeas_data" title="<?php echo $this->__('Autoriza Habeas Data') ?>" value="1" id="habeas_data"<?php if($this->getFormData()->getHabeasData()): ?> checked="checked"<?php endif; ?> class="checkbox required-entry" />
                        </div>
                        <label for="habeas_data"><?php echo $this->__('Autoriza Habeas Data') ?></label>
                    </div>
                </li>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset col-lg-6 col-md-6">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="company" class="required"><em>*</em><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="industry" class="required"><em>*</em><?php echo $this->__('Especialidad') ?></label>
                        <div class="input-box">
                            <?php
                            $attribute = Mage::getModel('eav/config')->getAttribute('customer_address', 'industry');
                            $options = $attribute->getSource()->getAllOptions(false);
                            ?>
                            <select id="industry" name="industry" title="<?php echo $this->__('Especialidad') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Seleccione Especialidad') ?></option>
                                <?php
                                foreach($options as $option){
                                    ?>
                                    <option value='<?php echo $option['value']?>' <?php if($this->getFormData()->getIndustry() == $option['value']){ echo 'selected="selected"';}?>><?php echo $this->__($option['label'])?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="area"><?php echo $this->__('Area') ?></label>
                        <div class="input-box">
                            <input type="text" name="area" value="<?php echo $this->htmlEscape($this->getFormData()->getArea()) ?>" title="<?php echo $this->__('Area') ?>" class="input-text" id="area" />
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="title"><?php echo $this->__('Title') ?></label>
                        <div class="input-box">
                            <input type="text" name="title" value="<?php echo $this->htmlEscape($this->getFormData()->getTitle()) ?>" title="<?php echo $this->__('Title') ?>" class="input-text" id="title" />
                        </div>
                    </div>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="website"><?php echo $this->__('Website') ?></label>
                        <div class="input-box">
                            <input type="text" name="website" value="<?php echo $this->htmlEscape($this->getFormData()->getWebsite()) ?>" title="<?php echo $this->__('Website') ?>" class="input-text" id="website" />
                        </div>
                    </div>
                </li>
                <li class="wide row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="locality"><?php echo $this->__('Localidad') ?></label>
                        <div class="input-box">
                            <?php
                            $attribute = Mage::getModel('eav/config')->getAttribute('customer_address', 'locality');
                            $options = $attribute->getSource()->getAllOptions(false);
                            ?>
                            <select id="locality" name="locality" title="<?php echo $this->__('Localidad') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Seleccione Localidad') ?></option>
                                <?php
                                foreach($options as $option){
                                    ?>
                                    <option value='<?php echo $option['value']?>' <?php if($this->getFormData()->getIndustry() == $option['value']){ echo 'selected="selected"';}?>><?php echo $this->__($option['label'])?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                </li>
            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                    </div>
                </li>
            <?php endfor ?>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                </li>
                <li class="fields row">
                    <div class="field col-md-6 col-sm-6">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                    <div class="field col-md-6 col-sm-6">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Seleccione Departamento') ?></option>
                            </select>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
		
		</div>
		
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
        <?php if ($isContextCheckout): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
		
		
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
