<?php
/**
 * Tawk.to
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@tawk.to so we can send you a copy immediately.
 *
 * @copyright   Copyright (c) 2014 Tawk.to
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div>herfoxbla bla</div>
<!--Start of Tawk.to Script-->
<script type="text/javascript"> var $_Tawk_API={},$_Tawk_LoadStart=new Date();
(function(){
	var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='<?php echo $this->getEmbedUrl() ?>';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
	s0.jlj=false;
})();
</script>
<?php if ($this->helper('customer')->isLoggedIn()) : ?>
<?php $current_user = $this->helper('customer')->getCustomer(); ?>
<?php echo "<script>Tawk_API = Tawk_API || {}; Tawk_API.visitor = { name  : '{$current_user->getName()}', email : '{$current_user->getEmail()}' };</script>"; ?>
<?php else: ?>
<?php echo "<script>Tawk_API = Tawk_API || {}; Tawk_API.hideWidget();</script>"; ?>
<?php endif; ?>
<!--End of Tawk.to Script-->