
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
<?php echo $this->__('Listo Pago a Plazos, es la nueva solución de Refinancia en alianza con Fenalco a través de la cual usted puede realizar sus compras a plazos sin preocuparse por el efectivo, sin tanto papeleo, sin cuota de manejo y con aprobación en una hora.'); ?>
<br /><br />
<?php echo $this->__('Para obtener este opción de pago <a href="#" target="_blank">haz click acá</a> y uno de nuestros asesores te visitará.'); ?>
        <br /><br />
        <img src="/media/wysiwyg/payment/logos-listo-fenalco.jpg" />
    </li>
</ul>
<!-- div>
    <?php // echo $this->getMethod()->getConfigData('message');?>
</div -->